/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const PastLazyRouteImport = createFileRoute('/past')()
const OrderLazyRouteImport = createFileRoute('/Order')()
const CartLazyRouteImport = createFileRoute('/Cart')()

const PastLazyRoute = PastLazyRouteImport.update({
  id: '/past',
  path: '/past',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/past.lazy').then((d) => d.Route))
const OrderLazyRoute = OrderLazyRouteImport.update({
  id: '/Order',
  path: '/Order',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/Order.lazy').then((d) => d.Route))
const CartLazyRoute = CartLazyRouteImport.update({
  id: '/Cart',
  path: '/Cart',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/Cart.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Cart': typeof CartLazyRoute
  '/Order': typeof OrderLazyRoute
  '/past': typeof PastLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Cart': typeof CartLazyRoute
  '/Order': typeof OrderLazyRoute
  '/past': typeof PastLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Cart': typeof CartLazyRoute
  '/Order': typeof OrderLazyRoute
  '/past': typeof PastLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Cart' | '/Order' | '/past'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Cart' | '/Order' | '/past'
  id: '__root__' | '/' | '/Cart' | '/Order' | '/past'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartLazyRoute: typeof CartLazyRoute
  OrderLazyRoute: typeof OrderLazyRoute
  PastLazyRoute: typeof PastLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/past': {
      id: '/past'
      path: '/past'
      fullPath: '/past'
      preLoaderRoute: typeof PastLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Order': {
      id: '/Order'
      path: '/Order'
      fullPath: '/Order'
      preLoaderRoute: typeof OrderLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Cart': {
      id: '/Cart'
      path: '/Cart'
      fullPath: '/Cart'
      preLoaderRoute: typeof CartLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartLazyRoute: CartLazyRoute,
  OrderLazyRoute: OrderLazyRoute,
  PastLazyRoute: PastLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
