/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const PastordersLazyRouteImport = createFileRoute('/pastorders')()
const OrderLazyRouteImport = createFileRoute('/Order')()
const CartLazyRouteImport = createFileRoute('/Cart')()
const IndexLazyRouteImport = createFileRoute('/')()

const PastordersLazyRoute = PastordersLazyRouteImport.update({
  id: '/pastorders',
  path: '/pastorders',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/pastorders.lazy').then((d) => d.Route))
const OrderLazyRoute = OrderLazyRouteImport.update({
  id: '/Order',
  path: '/Order',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/Order.lazy').then((d) => d.Route))
const CartLazyRoute = CartLazyRouteImport.update({
  id: '/Cart',
  path: '/Cart',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/Cart.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/Cart': typeof CartLazyRoute
  '/Order': typeof OrderLazyRoute
  '/pastorders': typeof PastordersLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/Cart': typeof CartLazyRoute
  '/Order': typeof OrderLazyRoute
  '/pastorders': typeof PastordersLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/Cart': typeof CartLazyRoute
  '/Order': typeof OrderLazyRoute
  '/pastorders': typeof PastordersLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Cart' | '/Order' | '/pastorders'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Cart' | '/Order' | '/pastorders'
  id: '__root__' | '/' | '/Cart' | '/Order' | '/pastorders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CartLazyRoute: typeof CartLazyRoute
  OrderLazyRoute: typeof OrderLazyRoute
  PastordersLazyRoute: typeof PastordersLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pastorders': {
      id: '/pastorders'
      path: '/pastorders'
      fullPath: '/pastorders'
      preLoaderRoute: typeof PastordersLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Order': {
      id: '/Order'
      path: '/Order'
      fullPath: '/Order'
      preLoaderRoute: typeof OrderLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Cart': {
      id: '/Cart'
      path: '/Cart'
      fullPath: '/Cart'
      preLoaderRoute: typeof CartLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CartLazyRoute: CartLazyRoute,
  OrderLazyRoute: OrderLazyRoute,
  PastordersLazyRoute: PastordersLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
